post http://localhost:4000/user-api/sellers
Content-Type: application/json

{
  "Company": "Flipkart",
  "Country": "India",
  "CountryCode": "91",
  "FirstName": "rajesh",
  "Gender": "male",
  "LastName": "k",
  "Mobile": "9014958056",
  "check": true,
  "email": "rajesh@gmail.com",
  "password": "$2a$05$AG3h2DPCvYEBQVglRxTm8OZDz7jWuFt/msU1JSlZOwyr87oxhDOCi",
  "state": "Andhra"
}
###
POST https://crackers-distribution-ecommerce-app.vercel.app/user-api/Register
Content-Type: application/json

{
  "FirstName": "kumari",
  "LastName": "lova",
  "email": "dlkumari16@gmail.com",
  "Locality": "pedawaltair vizag",
  "Village/cityName": "",
  "ZipCode": "",
  "state": "Andhra",
  "Country": "India",
  "DOB": "1983-07-23",
  "Gender": "female",
  "CountryCode": "91",
  "Mobile": "7893085299",
  "password": "kumari",
  "check": true
}